server:
  port: 8002
mybatis:
  type-aliases-package: com.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    cache-enabled: true

spring:
  application:
    name: springcloud-devt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456

#eureka的配置
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7003/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: springcloud_dept_8002
info:
  app.name: anhua-springcloud-dept8002
  company.name: anhua.com
